Add clear button
TN1ck/super-sudoku pull request #3
Opened 2023-02-26 19:10 UTC by hollow-owl

Add a clear button that clears the board but doesn't reset the time, so you don' have to complete the Sudoku to restart it.

2023-02-27 09:02 UTC, TN1ck requested changes
Thanks so much for the PR!

I have some question about the need of clearGame and there is an obsolete console.log.

2023-02-27 09:02 UTC, TN1ck commented on src/components/pages/Game/index.tsx
> +      );
I'm wondering why you send these parameters along to clear the game, currently cleargame resets the following:

* activeCellCoordinates
* notesMode
* showCircleMenu
* showHints: false
* showWrongEntries
* showMenu
* showNotes
* state (sets it to paused)
* won (sets it to false)
(All of these are actually UI settings, which I should in generally put somewhere else, but that's another topic)

The others are provided in clearGame as parameters and are the same as the ones in the store.
As I see it the actually logic are the next lines, where you set the sudoku.

Or am I missing something?

2023-02-27 09:02 UTC, TN1ck commented on src/components/pages/Game/index.tsx
> +      console.log("clearing");
remove this.

2023-02-27 20:17 UTC, hollow-owl commented
I copied from restartGame, but I don't really know how it works. I removed everything but
```js
      const sudoku = SUDOKUS[this.props.game.difficulty][this.props.game.sudokuIndex];
      this.props.setSudoku(sudoku.sudoku, sudoku.solution);
      this.props.continueGame();
```
which seems to work.

2023-02-27 21:06 UTC, TN1ck commented
> I copied from restartGame, but I don't really know how it works. I removed everything but
> 
> ```js
>       const sudoku = SUDOKUS[this.props.game.difficulty][this.props.game.sudokuIndex];
>       this.props.setSudoku(sudoku.sudoku, sudoku.solution);
>       this.props.continueGame();
> ```
> 
> which seems to work.

Cool thanks, that's nice!

About the feature in general - is that a common sudoku app thing? I guess resetting a game without finishing it and also resetting the timer is a bit cheating, so that the timer continues makes sense.
I do wonder if a "Are you sure?" after clicking would be beneficial, it seems easy to fat finger and lose your progress.
What do you think? I would add that myself before merging, so no worries.

2023-02-28 00:02 UTC, hollow-owl commented
Usually there's a restart/clear function. Sometimes it restarts the timer sometimes it doesn't. I think an "Are you sure?" would be helpful

2023-02-28 21:57 UTC, merged